# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4 , 5, 6, 7, 8, 9])
arr = arr.reshape((2,5))
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [22]:

arr1 = np.array([[0, 1, 2, 3, 4],
                [5, 6, 7, 8, 9]])
arr2 = np.ones((2,5))
arr3 = np.vstack((arr1,arr2))
arr3 = arr3.astype('int32')
print(arr3)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [23]:
arr1 = np.array([[0, 1, 2, 3, 4],
                [5, 6, 7, 8, 9]])
arr2 = np.ones((2,5))
arr4 = np.hstack((arr1,arr2))
arr4 = arr4.astype('int32')
print(arr4)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [19]:
a = arr.flatten()
print(a)

[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [15]:
arr5 = np.array([
    [ 0, 1, 2],
    [ 3, 4, 5],
    [ 6, 7, 8],
    [ 9, 10, 11],
    [12, 13, 14]
])
arr5 = np.ravel(arr5)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [17]:
arr5 = np.array([ 0 , 1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 ,10 ,11 ,12 ,13 ,14])
arr5.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [18]:
arr6 = np.random.randint(1,25, size = (5,5))
print("Original Array: \n")
print (arr6)
print("\n")
print("Square of Array: \n")
print(arr6 ** 2)

Original Array: 

[[23 11  6 17 15]
 [10 23 21 17 23]
 [ 3 21  2 21  3]
 [ 8  1 14 20  5]
 [ 4 18  3 22  8]]


Square of Array: 

[[529 121  36 289 225]
 [100 529 441 289 529]
 [  9 441   4 441   9]
 [ 64   1 196 400  25]
 [ 16 324   9 484  64]]


## Question:8

### Create 5x6 an array and find the mean?

In [ ]:
arr8 = np.random.randint(1,20, size = (5,6))
print("Original Array: \n")
print (arr8)
print("\n")
print("Mean of Array: \n")
print(arr8.mean())

## Question:9

### Find the standard deviation of the previous array in Q8?

In [ ]:
arr8 = np.random.randint(1,20, size = (5,6))
print("Original Array: \n")
print (arr8)
print("\n")
print("Standard deviation of Array: \n")
print(np.std(arr8))

## Question:10

### Find the median of the previous array in Q8?

In [ ]:
arr8 = np.random.randint(1,20, size = (5,6))
print("Original Array: \n")
print (arr8)
print("\n")
print("Median of Array: \n")
print(np.median(arr8))

## Question:11

### Find the transpose of the previous array in Q8?

In [10]:
arr8 = np.random.randint(1,20, size = (5,6))
print("Original Array: \n")
print (arr8)
print("\n")
print("Transpose of Array: \n")
print(np.transpose(arr8))


Original Array: 

[[ 5 12 10  6 18  9]
 [ 5  9 11  1  4 15]
 [ 3  2  9  8 17  2]
 [15 15  8 14 13  6]
 [ 9  9 16  3 11  3]]


Transpose of Array: 

[[ 5  5  3 15  9]
 [12  9  2 15  9]
 [10 11  9  8 16]
 [ 6  1  8 14  3]
 [18  4 17 13 11]
 [ 9 15  2  6  3]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [11]:
arr7 = np.random.randint(1,20, size = (4,4))
print("Original Array: \n")
print (arr7)
print("\n")
print("Sum of diagonal elements of Array: \n")
print(np.trace(arr7))

Original Array: 

[[12 15  6 16]
 [ 9 18  8  9]
 [19 11  4 15]
 [ 1  6  3 17]]


Sum of diagonal elements of Array: 

51


## Question:13

### Find the determinant of the previous array in Q12?

In [12]:
arr7 = np.random.randint(1,20, size = (4,4))
print("Original Array: \n")

print (arr7)
print("\n")
print("Determinant of Array: \n")
print(np.linalg.det(arr7))

Original Array: 

[[11  4 16 10]
 [11 14  6  1]
 [ 9  2  5 12]
 [ 8  3 17 13]]


Determinant of Array: 

-7586.999999999997


## Question:14

### Find the 5th and 95th percentile of an array?

In [9]:
arr7 = np.random.randint(1,20, size = (4,4))
print("Original Array: \n")
print (arr7)
print("\n")
print(f"5th percentile of array: {np.percentile(arr7, 5)}")
print(f"95th percentile of array: {np.percentile(arr7, 95)}")

Original Array: 

[[ 8 15  9 14]
 [ 4  8  7 13]
 [11  5 18  1]
 [12 10 13 18]]


5th percentile of array: 3.25
95th percentile of array: 18.0


## Question:15

### How to find if a given array has any null values?

In [5]:
arr7 = np.array([])
np.isnan(arr7).any()

False